In [12]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32


float32


In [13]:
arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

[1 2 3]


In [17]:
my_arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]] ,dtype="float32")

In [18]:
my_arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [19]:
int = my_arr.astype('int32')

In [20]:
int

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])