In [1]:
import numpy as np

In [2]:
# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
