In [4]:
import numpy as np

In [6]:
np.zeros((3, 3))    # 3x3 array of zeros


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:

np.ones((2, 4))     # 2x4 array of ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.full((2, 2), 7)  # 2x2 array filled with 7


array([[7, 7],
       [7, 7]])

In [9]:
np.eye(4)           # 4x4 identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)


array([1, 3, 5, 7, 9])

In [11]:
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])