In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [5]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [6]:
flat=arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat[0]

1

In [9]:
flat[3:6]

array([4, 5, 6])

In [10]:
flat[:5]

array([1, 2, 3, 4, 5])

In [11]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
b=flat[3:7]    #numpy copy nii bnata hai ye view return krta hai jo chane hm b mein krenge vo flat mein change ho jyega

In [14]:
b

array([4, 5, 6, 7])

In [15]:
b[0]=4444

In [16]:
b

array([4444,    5,    6,    7])

In [17]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [18]:
b=flat[3:7].copy() # to ye copy bnayega isko ab slicing ni bolenge or flatten change ni hoga

In [19]:
b

array([4444,    5,    6,    7])

In [20]:
b[0]=2

In [21]:
b

array([2, 5, 6, 7])

In [22]:
flat                         # flat change nii hua jb ki hmne b[0] ko change kr diya tha 

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [25]:
arr = np.array([1,5,88,78,26,89])# fancy indexing

In [27]:
arr[[0,4,5]]  #in index mein jo bhi element ka array bna k de dega

array([ 1, 26, 89])

In [32]:
arr1

NameError: name 'arr1' is not defined